# mf7.82.room.light.luxlevel1_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.luxlevel1_782 -d '{"serinstid":"serinst.luxlevel1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.luxlevel1_782 -d '{"serinstname":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.luxlevel1_782 -d '{"serinstservicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.room -d '{"serinst.luxlevel1_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.luxlevel1_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/light -d '{"serinst.luxlevel1_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevel1_782 -d '{"varid":"luxlevel1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevel1_782 -d '{"varname":"luxlevel1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevel1_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevel1_782 -d '{"domainstates": {"range":{"min":"0","max":"30000","step":"10"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevel1_782 -d '{"servicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevel1_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevel1_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevel1_782 -d '{"routingkey":"metaforum.floor7.room782.room.light.luxlevel1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevel1_782 -d '{"varlocation":"mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.room -d '{"luxlevel1_782":"luxlevel1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/light -d '{"luxlevel1_782":"luxlevel1_782"}' -H 'Content-Type:"application/json"'

# mf7.82.room.light.luxlevelout1_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.luxlevelout1_782 -d '{"serinstid":"serinst.luxlevelout1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.luxlevelout1_782 -d '{"serinstname":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.luxlevelout1_782 -d '{"serinstservicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.room -d '{"serinst.luxlevelout1_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.luxlevelout1_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/light -d '{"serinst.luxlevelout1_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevelout1_782 -d '{"varid":"luxlevelout1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevelout1_782 -d '{"varname":"luxlevelout1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevelout1_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevelout1_782 -d '{"domainstates": {"range":{"min":"0","max":"30000","step":"10"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevelout1_782 -d '{"servicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevelout1_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevelout1_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevelout1_782 -d '{"routingkey":"metaforum.floor7.room782.room.light.luxlevelout1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/luxlevelout1_782 -d '{"varlocation":"mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.room -d '{"luxlevelout1_782":"luxlevelout1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/light -d '{"luxlevelout1_782":"luxlevelout1_782"}' -H 'Content-Type:"application/json"'

