# mf7.82.desk1.powerconsumption1_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption1_782 -d '{"serinstid":"serinst.powerconsumption1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption1_782 -d '{"serinstname":"powerconsumption.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption1_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk1 -d '{"serinst.powerconsumption1_782":"powerconsumption.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption1_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption1_782":"powerconsumption.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption1_782 -d '{"varid":"powerconsumption1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption1_782 -d '{"varname":"powerconsumption1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption1_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption1_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption1_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption1_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption1_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption1_782 -d '{"routingkey":"metaforum.floor7.room782.desk1.powerconsumption.powerconsumption1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption1_782 -d '{"varlocation":"mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk1 -d '{"powerconsumption1_782":"powerconsumption1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption1_782":"powerconsumption1_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk2.powerconsumption2_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption2_782 -d '{"serinstid":"serinst.powerconsumption2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption2_782 -d '{"serinstname":"powerconsumption.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption2_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk2 -d '{"serinst.powerconsumption2_782":"powerconsumption.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption2_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption2_782":"powerconsumption.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption2_782 -d '{"varid":"powerconsumption2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption2_782 -d '{"varname":"powerconsumption2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption2_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption2_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption2_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption2_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption2_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption2_782 -d '{"routingkey":"metaforum.floor7.room782.desk2.powerconsumption.powerconsumption2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption2_782 -d '{"varlocation":"mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk2 -d '{"powerconsumption2_782":"powerconsumption2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption2_782":"powerconsumption2_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk3.powerconsumption3_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption3_782 -d '{"serinstid":"serinst.powerconsumption3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption3_782 -d '{"serinstname":"powerconsumption.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption3_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk3 -d '{"serinst.powerconsumption3_782":"powerconsumption.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption3_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption3_782":"powerconsumption.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption3_782 -d '{"varid":"powerconsumption3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption3_782 -d '{"varname":"powerconsumption3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption3_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption3_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption3_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption3_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption3_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption3_782 -d '{"routingkey":"metaforum.floor7.room782.desk3.powerconsumption.powerconsumption3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption3_782 -d '{"varlocation":"mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk3 -d '{"powerconsumption3_782":"powerconsumption3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption3_782":"powerconsumption3_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk4.powerconsumption4_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption4_782 -d '{"serinstid":"serinst.powerconsumption4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption4_782 -d '{"serinstname":"powerconsumption.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption4_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk4 -d '{"serinst.powerconsumption4_782":"powerconsumption.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption4_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption4_782":"powerconsumption.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption4_782 -d '{"varid":"powerconsumption4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption4_782 -d '{"varname":"powerconsumption4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption4_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption4_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption4_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption4_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption4_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption4_782 -d '{"routingkey":"metaforum.floor7.room782.desk4.powerconsumption.powerconsumption4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption4_782 -d '{"varlocation":"mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk4 -d '{"powerconsumption4_782":"powerconsumption4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption4_782":"powerconsumption4_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk5.powerconsumption5_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption5_782 -d '{"serinstid":"serinst.powerconsumption5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption5_782 -d '{"serinstname":"powerconsumption.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption5_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk5 -d '{"serinst.powerconsumption5_782":"powerconsumption.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption5_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption5_782":"powerconsumption.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption5_782 -d '{"varid":"powerconsumption5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption5_782 -d '{"varname":"powerconsumption5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption5_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption5_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption5_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption5_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption5_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption5_782 -d '{"routingkey":"metaforum.floor7.room782.desk5.powerconsumption.powerconsumption5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption5_782 -d '{"varlocation":"mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk5 -d '{"powerconsumption5_782":"powerconsumption5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption5_782":"powerconsumption5_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk6.powerconsumption6_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption6_782 -d '{"serinstid":"serinst.powerconsumption6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption6_782 -d '{"serinstname":"powerconsumption.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption6_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk6 -d '{"serinst.powerconsumption6_782":"powerconsumption.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption6_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption6_782":"powerconsumption.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption6_782 -d '{"varid":"powerconsumption6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption6_782 -d '{"varname":"powerconsumption6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption6_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption6_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption6_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption6_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption6_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption6_782 -d '{"routingkey":"metaforum.floor7.room782.desk6.powerconsumption.powerconsumption6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption6_782 -d '{"varlocation":"mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk6 -d '{"powerconsumption6_782":"powerconsumption6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption6_782":"powerconsumption6_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk7.powerconsumption7_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption7_782 -d '{"serinstid":"serinst.powerconsumption7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption7_782 -d '{"serinstname":"powerconsumption.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption7_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk7 -d '{"serinst.powerconsumption7_782":"powerconsumption.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption7_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption7_782":"powerconsumption.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption7_782 -d '{"varid":"powerconsumption7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption7_782 -d '{"varname":"powerconsumption7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption7_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption7_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption7_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption7_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption7_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption7_782 -d '{"routingkey":"metaforum.floor7.room782.desk7.powerconsumption.powerconsumption7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption7_782 -d '{"varlocation":"mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk7 -d '{"powerconsumption7_782":"powerconsumption7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption7_782":"powerconsumption7_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk8.powerconsumption8_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption8_782 -d '{"serinstid":"serinst.powerconsumption8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption8_782 -d '{"serinstname":"powerconsumption.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption8_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk8 -d '{"serinst.powerconsumption8_782":"powerconsumption.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption8_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption8_782":"powerconsumption.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption8_782 -d '{"varid":"powerconsumption8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption8_782 -d '{"varname":"powerconsumption8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption8_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption8_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption8_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption8_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption8_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption8_782 -d '{"routingkey":"metaforum.floor7.room782.desk8.powerconsumption.powerconsumption8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption8_782 -d '{"varlocation":"mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk8 -d '{"powerconsumption8_782":"powerconsumption8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption8_782":"powerconsumption8_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk9.powerconsumption9_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption9_782 -d '{"serinstid":"serinst.powerconsumption9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption9_782 -d '{"serinstname":"powerconsumption.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption9_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk9 -d '{"serinst.powerconsumption9_782":"powerconsumption.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption9_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption9_782":"powerconsumption.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption9_782 -d '{"varid":"powerconsumption9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption9_782 -d '{"varname":"powerconsumption9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption9_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption9_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption9_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption9_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption9_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption9_782 -d '{"routingkey":"metaforum.floor7.room782.desk9.powerconsumption.powerconsumption9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption9_782 -d '{"varlocation":"mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk9 -d '{"powerconsumption9_782":"powerconsumption9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption9_782":"powerconsumption9_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk10.powerconsumption10_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption10_782 -d '{"serinstid":"serinst.powerconsumption10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption10_782 -d '{"serinstname":"powerconsumption.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption10_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk10 -d '{"serinst.powerconsumption10_782":"powerconsumption.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption10_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption10_782":"powerconsumption.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption10_782 -d '{"varid":"powerconsumption10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption10_782 -d '{"varname":"powerconsumption10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption10_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption10_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption10_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption10_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption10_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption10_782 -d '{"routingkey":"metaforum.floor7.room782.desk10.powerconsumption.powerconsumption10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption10_782 -d '{"varlocation":"mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk10 -d '{"powerconsumption10_782":"powerconsumption10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption10_782":"powerconsumption10_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk11.powerconsumption11_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption11_782 -d '{"serinstid":"serinst.powerconsumption11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption11_782 -d '{"serinstname":"powerconsumption.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption11_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk11 -d '{"serinst.powerconsumption11_782":"powerconsumption.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption11_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption11_782":"powerconsumption.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption11_782 -d '{"varid":"powerconsumption11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption11_782 -d '{"varname":"powerconsumption11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption11_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption11_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption11_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption11_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption11_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption11_782 -d '{"routingkey":"metaforum.floor7.room782.desk11.powerconsumption.powerconsumption11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption11_782 -d '{"varlocation":"mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk11 -d '{"powerconsumption11_782":"powerconsumption11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption11_782":"powerconsumption11_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk12.powerconsumption12_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption12_782 -d '{"serinstid":"serinst.powerconsumption12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption12_782 -d '{"serinstname":"powerconsumption.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption12_782 -d '{"serinstservicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk12 -d '{"serinst.powerconsumption12_782":"powerconsumption.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.powerconsumption12_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/powerconsumption -d '{"serinst.powerconsumption12_782":"powerconsumption.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption12_782 -d '{"varid":"powerconsumption12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption12_782 -d '{"varname":"powerconsumption12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption12_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption12_782 -d '{"domainstates":{"range":{"min":"0","max":"1320","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption12_782 -d '{"servicetype":"powerconsumption"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption12_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption12_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption12_782 -d '{"routingkey":"metaforum.floor7.room782.desk12.powerconsumption.powerconsumption12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/powerconsumption12_782 -d '{"varlocation":"mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk12 -d '{"powerconsumption12_782":"powerconsumption12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/powerconsumption -d '{"powerconsumption12_782":"powerconsumption12_782"}' -H 'Content-Type:"application/json"'

