# mf7.82.desk1.presenceUSR1_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR1_782 -d '{"serinstid":"serinst.presenceUSR1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR1_782 -d '{"serinstname":"presence.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR1_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk1 -d '{"serinst.presenceUSR1_782":"presence.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR1_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR1_782":"presence.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR1_782 -d '{"varid":"presenceUSR1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR1_782 -d '{"varname":"presenceUSR1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR1_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR1_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR1_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR1_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR1_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR1_782 -d '{"routingkey":"metaforum.floor7.room782.desk1.presenceUSR1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR1_782 -d '{"varlocation":"mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk1 -d '{"presenceUSR1_782":"presenceUSR1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR1_782":"presenceUSR1_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk1.presenceUSR2_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR2_782 -d '{"serinstid":"serinst.presenceUSR2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR2_782 -d '{"serinstname":"presence.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR2_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk1 -d '{"serinst.presenceUSR2_782":"presence.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR2_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR2_782":"presence.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR2_782 -d '{"varid":"presenceUSR2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR2_782 -d '{"varname":"presenceUSR2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR2_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR2_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR2_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR2_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR2_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR2_782 -d '{"routingkey":"metaforum.floor7.room782.desk1.presenceUSR2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR2_782 -d '{"varlocation":"mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk1 -d '{"presenceUSR2_782":"presenceUSR2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR2_782":"presenceUSR2_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk2.presenceUSR3_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR3_782 -d '{"serinstid":"serinst.presenceUSR3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR3_782 -d '{"serinstname":"presence.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR3_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk2 -d '{"serinst.presenceUSR3_782":"presence.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR3_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR3_782":"presence.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR3_782 -d '{"varid":"presenceUSR3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR3_782 -d '{"varname":"presenceUSR3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR3_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR3_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR3_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR3_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR3_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR3_782 -d '{"routingkey":"metaforum.floor7.room782.desk2.presenceUSR3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR3_782 -d '{"varlocation":"mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk2 -d '{"presenceUSR3_782":"presenceUSR3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR3_782":"presenceUSR3_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk2.presenceUSR4_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR4_782 -d '{"serinstid":"serinst.presenceUSR4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR4_782 -d '{"serinstname":"presence.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR4_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk2 -d '{"serinst.presenceUSR4_782":"presence.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR4_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR4_782":"presence.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR4_782 -d '{"varid":"presenceUSR4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR4_782 -d '{"varname":"presenceUSR4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR4_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR4_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR4_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR4_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR4_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR4_782 -d '{"routingkey":"metaforum.floor7.room782.desk2.presenceUSR4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR4_782 -d '{"varlocation":"mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk2 -d '{"presenceUSR4_782":"presenceUSR4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR4_782":"presenceUSR4_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk3.presenceUSR5_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR5_782 -d '{"serinstid":"serinst.presenceUSR5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR5_782 -d '{"serinstname":"presence.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR5_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk3 -d '{"serinst.presenceUSR5_782":"presence.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR5_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR5_782":"presence.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR5_782 -d '{"varid":"presenceUSR5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR5_782 -d '{"varname":"presenceUSR5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR5_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR5_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR5_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR5_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR5_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR5_782 -d '{"routingkey":"metaforum.floor7.room782.desk3.presenceUSR5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR5_782 -d '{"varlocation":"mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk3 -d '{"presenceUSR5_782":"presenceUSR5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR5_782":"presenceUSR5_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk3.presenceUSR6_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR6_782 -d '{"serinstid":"serinst.presenceUSR6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR6_782 -d '{"serinstname":"presence.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR6_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk3 -d '{"serinst.presenceUSR6_782":"presence.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR6_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR6_782":"presence.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR6_782 -d '{"varid":"presenceUSR6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR6_782 -d '{"varname":"presenceUSR6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR6_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR6_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR6_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR6_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR6_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR6_782 -d '{"routingkey":"metaforum.floor7.room782.desk3.presenceUSR6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR6_782 -d '{"varlocation":"mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk3 -d '{"presenceUSR6_782":"presenceUSR6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR6_782":"presenceUSR6_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk4.presenceUSR7_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR7_782 -d '{"serinstid":"serinst.presenceUSR7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR7_782 -d '{"serinstname":"presence.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR7_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk4 -d '{"serinst.presenceUSR7_782":"presence.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR7_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR7_782":"presence.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR7_782 -d '{"varid":"presenceUSR7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR7_782 -d '{"varname":"presenceUSR7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR7_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR7_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR7_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR7_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR7_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR7_782 -d '{"routingkey":"metaforum.floor7.room782.desk4.presenceUSR7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR7_782 -d '{"varlocation":"mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk4 -d '{"presenceUSR7_782":"presenceUSR7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR7_782":"presenceUSR7_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk4.presenceUSR8_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR8_782 -d '{"serinstid":"serinst.presenceUSR8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR8_782 -d '{"serinstname":"presence.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR8_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk4 -d '{"serinst.presenceUSR8_782":"presence.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR8_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR8_782":"presence.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR8_782 -d '{"varid":"presenceUSR8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR8_782 -d '{"varname":"presenceUSR8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR8_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR8_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR8_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR8_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR8_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR8_782 -d '{"routingkey":"metaforum.floor7.room782.desk4.presenceUSR8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR8_782 -d '{"varlocation":"mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk4 -d '{"presenceUSR8_782":"presenceUSR8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR8_782":"presenceUSR8_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk5.presenceUSR9_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR9_782 -d '{"serinstid":"serinst.presenceUSR9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR9_782 -d '{"serinstname":"presence.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR9_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk5 -d '{"serinst.presenceUSR9_782":"presence.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR9_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR9_782":"presence.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR9_782 -d '{"varid":"presenceUSR9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR9_782 -d '{"varname":"presenceUSR9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR9_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR9_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR9_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR9_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR9_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR9_782 -d '{"routingkey":"metaforum.floor7.room782.desk5.presenceUSR9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR9_782 -d '{"varlocation":"mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk5 -d '{"presenceUSR9_782":"presenceUSR9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR9_782":"presenceUSR9_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk5.presenceUSR10_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR10_782 -d '{"serinstid":"serinst.presenceUSR10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR10_782 -d '{"serinstname":"presence.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR10_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk5 -d '{"serinst.presenceUSR10_782":"presence.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR10_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR10_782":"presence.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR10_782 -d '{"varid":"presenceUSR10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR10_782 -d '{"varname":"presenceUSR10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR10_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR10_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR10_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR10_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR10_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR10_782 -d '{"routingkey":"metaforum.floor7.room782.desk5.presenceUSR10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR10_782 -d '{"varlocation":"mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk5 -d '{"presenceUSR10_782":"presenceUSR10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR10_782":"presenceUSR10_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk6.presenceUSR11_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR11_782 -d '{"serinstid":"serinst.presenceUSR11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR11_782 -d '{"serinstname":"presence.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR11_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk6 -d '{"serinst.presenceUSR11_782":"presence.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR11_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR11_782":"presence.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR11_782 -d '{"varid":"presenceUSR11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR11_782 -d '{"varname":"presenceUSR11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR11_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR11_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR11_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR11_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR11_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR11_782 -d '{"routingkey":"metaforum.floor7.room782.desk6.presenceUSR11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR11_782 -d '{"varlocation":"mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk6 -d '{"presenceUSR11_782":"presenceUSR11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR11_782":"presenceUSR11_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk6.presenceUSR12_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR12_782 -d '{"serinstid":"serinst.presenceUSR12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR12_782 -d '{"serinstname":"presence.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR12_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk6 -d '{"serinst.presenceUSR12_782":"presence.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR12_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR12_782":"presence.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR12_782 -d '{"varid":"presenceUSR12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR12_782 -d '{"varname":"presenceUSR12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR12_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR12_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR12_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR12_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR12_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR12_782 -d '{"routingkey":"metaforum.floor7.room782.desk6.presenceUSR12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR12_782 -d '{"varlocation":"mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk6 -d '{"presenceUSR12_782":"presenceUSR12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR12_782":"presenceUSR12_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk7.presenceUSR13_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR13_782 -d '{"serinstid":"serinst.presenceUSR13_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR13_782 -d '{"serinstname":"presence.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR13_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk7 -d '{"serinst.presenceUSR13_782":"presence.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR13_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR13_782":"presence.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR13_782 -d '{"varid":"presenceUSR13_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR13_782 -d '{"varname":"presenceUSR13_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR13_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR13_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR13_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR13_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR13_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR13_782 -d '{"routingkey":"metaforum.floor7.room782.desk7.presenceUSR13_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR13_782 -d '{"varlocation":"mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk7 -d '{"presenceUSR13_782":"presenceUSR13_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR13_782":"presenceUSR13_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk7.presenceUSR14_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR14_782 -d '{"serinstid":"serinst.presenceUSR14_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR14_782 -d '{"serinstname":"presence.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR14_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk7 -d '{"serinst.presenceUSR14_782":"presence.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR14_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR14_782":"presence.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR14_782 -d '{"varid":"presenceUSR14_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR14_782 -d '{"varname":"presenceUSR14_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR14_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR14_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR14_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR14_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR14_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR14_782 -d '{"routingkey":"metaforum.floor7.room782.desk7.presenceUSR14_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR14_782 -d '{"varlocation":"mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk7 -d '{"presenceUSR14_782":"presenceUSR14_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR14_782":"presenceUSR14_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk8.presenceUSR15_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR15_782 -d '{"serinstid":"serinst.presenceUSR15_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR15_782 -d '{"serinstname":"presence.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR15_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk8 -d '{"serinst.presenceUSR15_782":"presence.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR15_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR15_782":"presence.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR15_782 -d '{"varid":"presenceUSR15_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR15_782 -d '{"varname":"presenceUSR15_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR15_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR15_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR15_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR15_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR15_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR15_782 -d '{"routingkey":"metaforum.floor7.room782.desk8.presenceUSR15_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR15_782 -d '{"varlocation":"mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk8 -d '{"presenceUSR15_782":"presenceUSR15_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR15_782":"presenceUSR15_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk8.presenceUSR16_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR16_782 -d '{"serinstid":"serinst.presenceUSR16_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR16_782 -d '{"serinstname":"presence.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR16_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk8 -d '{"serinst.presenceUSR16_782":"presence.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR16_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR16_782":"presence.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR16_782 -d '{"varid":"presenceUSR16_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR16_782 -d '{"varname":"presenceUSR16_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR16_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR16_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR16_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR16_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR16_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR16_782 -d '{"routingkey":"metaforum.floor7.room782.desk8.presenceUSR16_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR16_782 -d '{"varlocation":"mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk8 -d '{"presenceUSR16_782":"presenceUSR16_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR16_782":"presenceUSR16_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk9.presenceUSR17_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR17_782 -d '{"serinstid":"serinst.presenceUSR17_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR17_782 -d '{"serinstname":"presence.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR17_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk9 -d '{"serinst.presenceUSR17_782":"presence.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR17_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR17_782":"presence.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR17_782 -d '{"varid":"presenceUSR17_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR17_782 -d '{"varname":"presenceUSR17_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR17_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR17_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR17_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR17_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR17_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR17_782 -d '{"routingkey":"metaforum.floor7.room782.desk9.presenceUSR17_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR17_782 -d '{"varlocation":"mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk9 -d '{"presenceUSR17_782":"presenceUSR17_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR17_782":"presenceUSR17_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk9.presenceUSR18_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR18_782 -d '{"serinstid":"serinst.presenceUSR18_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR18_782 -d '{"serinstname":"presence.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR18_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk9 -d '{"serinst.presenceUSR18_782":"presence.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR18_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR18_782":"presence.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR18_782 -d '{"varid":"presenceUSR18_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR18_782 -d '{"varname":"presenceUSR18_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR18_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR18_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR18_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR18_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR18_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR18_782 -d '{"routingkey":"metaforum.floor7.room782.desk9.presenceUSR18_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR18_782 -d '{"varlocation":"mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk9 -d '{"presenceUSR18_782":"presenceUSR18_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR18_782":"presenceUSR18_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk10.presenceUSR19_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR19_782 -d '{"serinstid":"serinst.presenceUSR19_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR19_782 -d '{"serinstname":"presence.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR19_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk10 -d '{"serinst.presenceUSR19_782":"presence.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR19_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR19_782":"presence.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR19_782 -d '{"varid":"presenceUSR19_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR19_782 -d '{"varname":"presenceUSR19_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR19_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR19_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR19_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR19_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR19_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR19_782 -d '{"routingkey":"metaforum.floor7.room782.desk10.presenceUSR19_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR19_782 -d '{"varlocation":"mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk10 -d '{"presenceUSR19_782":"presenceUSR19_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR19_782":"presenceUSR19_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk10.presenceUSR20_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR20_782 -d '{"serinstid":"serinst.presenceUSR20_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR20_782 -d '{"serinstname":"presence.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR20_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk10 -d '{"serinst.presenceUSR20_782":"presence.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR20_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR20_782":"presence.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR20_782 -d '{"varid":"presenceUSR20_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR20_782 -d '{"varname":"presenceUSR20_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR20_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR20_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR20_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR20_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR20_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR20_782 -d '{"routingkey":"metaforum.floor7.room782.desk10.presenceUSR20_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR20_782 -d '{"varlocation":"mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk10 -d '{"presenceUSR20_782":"presenceUSR20_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR20_782":"presenceUSR20_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk11.presenceUSR21_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR21_782 -d '{"serinstid":"serinst.presenceUSR21_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR21_782 -d '{"serinstname":"presence.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR21_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk11 -d '{"serinst.presenceUSR21_782":"presence.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR21_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR21_782":"presence.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR21_782 -d '{"varid":"presenceUSR21_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR21_782 -d '{"varname":"presenceUSR21_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR21_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR21_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR21_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR21_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR21_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR21_782 -d '{"routingkey":"metaforum.floor7.room782.desk11.presenceUSR21_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR21_782 -d '{"varlocation":"mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk11 -d '{"presenceUSR21_782":"presenceUSR21_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR21_782":"presenceUSR21_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk11.presenceUSR22_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR22_782 -d '{"serinstid":"serinst.presenceUSR22_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR22_782 -d '{"serinstname":"presence.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR22_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk11 -d '{"serinst.presenceUSR22_782":"presence.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR22_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR22_782":"presence.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR22_782 -d '{"varid":"presenceUSR22_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR22_782 -d '{"varname":"presenceUSR22_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR22_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR22_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR22_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR22_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR22_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR22_782 -d '{"routingkey":"metaforum.floor7.room782.desk11.presenceUSR22_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR22_782 -d '{"varlocation":"mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk11 -d '{"presenceUSR22_782":"presenceUSR22_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR22_782":"presenceUSR22_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk12.presenceUSR23_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR23_782 -d '{"serinstid":"serinst.presenceUSR23_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR23_782 -d '{"serinstname":"presence.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR23_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk12 -d '{"serinst.presenceUSR23_782":"presence.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR23_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR23_782":"presence.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR23_782 -d '{"varid":"presenceUSR23_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR23_782 -d '{"varname":"presenceUSR23_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR23_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR23_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR23_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR23_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR23_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR23_782 -d '{"routingkey":"metaforum.floor7.room782.desk12.presenceUSR23_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR23_782 -d '{"varlocation":"mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk12 -d '{"presenceUSR23_782":"presenceUSR23_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR23_782":"presenceUSR23_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk12.presenceUSR24_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR24_782 -d '{"serinstid":"serinst.presenceUSR24_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR24_782 -d '{"serinstname":"presence.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR24_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk12 -d '{"serinst.presenceUSR24_782":"presence.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presenceUSR24_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presenceUSR24_782":"presence.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR24_782 -d '{"varid":"presenceUSR24_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR24_782 -d '{"varname":"presenceUSR24_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR24_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR24_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR24_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR24_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR24_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR24_782 -d '{"routingkey":"metaforum.floor7.room782.desk12.presenceUSR24_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presenceUSR24_782 -d '{"varlocation":"mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk12 -d '{"presenceUSR24_782":"presenceUSR24_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presenceUSR24_782":"presenceUSR24_782"}' -H 'Content-Type:"application/json"'

