# mf7.82.room.light.lightpowerconsumption1_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption1_782 -d '{"serinstid":"serinst.lightpowerconsumption1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption1_782 -d '{"serinstname":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption1_782 -d '{"serinstservicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.room -d '{"serinst.lightpowerconsumption1_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption1_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/light -d '{"serinst.lightpowerconsumption1_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption1_782 -d '{"varid":"lightpowerconsumption1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption1_782 -d '{"varname":"lightpowerconsumption1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption1_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption1_782 -d '{"domainstates": {"range":{"min":"0","max":"200","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption1_782 -d '{"servicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption1_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption1_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption1_782 -d '{"routingkey":"metaforum.floor7.room782.room.light.lightpowerconsumption1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption1_782 -d '{"varlocation":"mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.room -d '{"lightpowerconsumption1_782":"lightpowerconsumption1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/light -d '{"lightpowerconsumption1_782":"lightpowerconsumption1_782"}' -H 'Content-Type:"application/json"'

# mf7.82.room.light.lightpowerconsumption2_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption2_782 -d '{"serinstid":"serinst.lightpowerconsumption2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption2_782 -d '{"serinstname":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption2_782 -d '{"serinstservicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.room -d '{"serinst.lightpowerconsumption2_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption2_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/light -d '{"serinst.lightpowerconsumption2_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption2_782 -d '{"varid":"lightpowerconsumption2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption2_782 -d '{"varname":"lightpowerconsumption2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption2_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption2_782 -d '{"domainstates": {"range":{"min":"0","max":"200","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption2_782 -d '{"servicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption2_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption2_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption2_782 -d '{"routingkey":"metaforum.floor7.room782.room.light.lightpowerconsumption2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption2_782 -d '{"varlocation":"mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.room -d '{"lightpowerconsumption2_782":"lightpowerconsumption2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/light -d '{"lightpowerconsumption2_782":"lightpowerconsumption2_782"}' -H 'Content-Type:"application/json"'

# mf7.82.room.light.lightpowerconsumption3_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption3_782 -d '{"serinstid":"serinst.lightpowerconsumption3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption3_782 -d '{"serinstname":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption3_782 -d '{"serinstservicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.room -d '{"serinst.lightpowerconsumption3_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption3_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/light -d '{"serinst.lightpowerconsumption3_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption3_782 -d '{"varid":"lightpowerconsumption3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption3_782 -d '{"varname":"lightpowerconsumption3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption3_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption3_782 -d '{"domainstates": {"range":{"min":"0","max":"200","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption3_782 -d '{"servicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption3_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption3_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption3_782 -d '{"routingkey":"metaforum.floor7.room782.room.light.lightpowerconsumption3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption3_782 -d '{"varlocation":"mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.room -d '{"lightpowerconsumption3_782":"lightpowerconsumption3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/light -d '{"lightpowerconsumption3_782":"lightpowerconsumption3_782"}' -H 'Content-Type:"application/json"'

# mf7.82.room.light.lightpowerconsumption4_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption4_782 -d '{"serinstid":"serinst.lightpowerconsumption4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption4_782 -d '{"serinstname":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption4_782 -d '{"serinstservicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.room -d '{"serinst.lightpowerconsumption4_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption4_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/light -d '{"serinst.lightpowerconsumption4_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption4_782 -d '{"varid":"lightpowerconsumption4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption4_782 -d '{"varname":"lightpowerconsumption4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption4_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption4_782 -d '{"domainstates": {"range":{"min":"0","max":"200","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption4_782 -d '{"servicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption4_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption4_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption4_782 -d '{"routingkey":"metaforum.floor7.room782.room.light.lightpowerconsumption4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption4_782 -d '{"varlocation":"mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.room -d '{"lightpowerconsumption4_782":"lightpowerconsumption4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/light -d '{"lightpowerconsumption4_782":"lightpowerconsumption4_782"}' -H 'Content-Type:"application/json"'

# mf7.82.room.light.lightpowerconsumption5_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption5_782 -d '{"serinstid":"serinst.lightpowerconsumption5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption5_782 -d '{"serinstname":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption5_782 -d '{"serinstservicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.room -d '{"serinst.lightpowerconsumption5_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption5_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/light -d '{"serinst.lightpowerconsumption5_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption5_782 -d '{"varid":"lightpowerconsumption5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption5_782 -d '{"varname":"lightpowerconsumption5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption5_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption5_782 -d '{"domainstates": {"range":{"min":"0","max":"200","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption5_782 -d '{"servicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption5_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption5_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption5_782 -d '{"routingkey":"metaforum.floor7.room782.room.light.lightpowerconsumption5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption5_782 -d '{"varlocation":"mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.room -d '{"lightpowerconsumption5_782":"lightpowerconsumption5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/light -d '{"lightpowerconsumption5_782":"lightpowerconsumption5_782"}' -H 'Content-Type:"application/json"'

# mf7.82.room.light.lightpowerconsumption6_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption6_782 -d '{"serinstid":"serinst.lightpowerconsumption6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption6_782 -d '{"serinstname":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption6_782 -d '{"serinstservicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.room -d '{"serinst.lightpowerconsumption6_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption6_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/light -d '{"serinst.lightpowerconsumption6_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption6_782 -d '{"varid":"lightpowerconsumption6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption6_782 -d '{"varname":"lightpowerconsumption6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption6_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption6_782 -d '{"domainstates": {"range":{"min":"0","max":"200","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption6_782 -d '{"servicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption6_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption6_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption6_782 -d '{"routingkey":"metaforum.floor7.room782.room.light.lightpowerconsumption6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption6_782 -d '{"varlocation":"mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.room -d '{"lightpowerconsumption6_782":"lightpowerconsumption6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/light -d '{"lightpowerconsumption6_782":"lightpowerconsumption6_782"}' -H 'Content-Type:"application/json"'

# mf7.82.room.light.lightpowerconsumption7_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption7_782 -d '{"serinstid":"serinst.lightpowerconsumption7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption7_782 -d '{"serinstname":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption7_782 -d '{"serinstservicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.room -d '{"serinst.lightpowerconsumption7_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption7_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/light -d '{"serinst.lightpowerconsumption7_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption7_782 -d '{"varid":"lightpowerconsumption7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption7_782 -d '{"varname":"lightpowerconsumption7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption7_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption7_782 -d '{"domainstates": {"range":{"min":"0","max":"200","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption7_782 -d '{"servicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption7_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption7_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption7_782 -d '{"routingkey":"metaforum.floor7.room782.room.light.lightpowerconsumption7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption7_782 -d '{"varlocation":"mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.room -d '{"lightpowerconsumption7_782":"lightpowerconsumption7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/light -d '{"lightpowerconsumption7_782":"lightpowerconsumption7_782"}' -H 'Content-Type:"application/json"'

# mf7.82.room.light.lightpowerconsumption8_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption8_782 -d '{"serinstid":"serinst.lightpowerconsumption8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption8_782 -d '{"serinstname":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption8_782 -d '{"serinstservicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.room -d '{"serinst.lightpowerconsumption8_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.lightpowerconsumption8_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/light -d '{"serinst.lightpowerconsumption8_782":"light.mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption8_782 -d '{"varid":"lightpowerconsumption8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption8_782 -d '{"varname":"lightpowerconsumption8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption8_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption8_782 -d '{"domainstates": {"range":{"min":"0","max":"200","step":"0.1"},"costa":"0","costb":"0"}}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption8_782 -d '{"servicetype":"light"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption8_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption8_782 -d '{"datatype":"float"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption8_782 -d '{"routingkey":"metaforum.floor7.room782.room.light.lightpowerconsumption8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/lightpowerconsumption8_782 -d '{"varlocation":"mf7.82.room"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.room -d '{"lightpowerconsumption8_782":"lightpowerconsumption8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/light -d '{"lightpowerconsumption8_782":"lightpowerconsumption8_782"}' -H 'Content-Type:"application/json"'

