# mf7.82.desk1.presence1_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence1_782 -d '{"serinstid":"serinst.presence1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence1_782 -d '{"serinstname":"presence.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence1_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk1 -d '{"serinst.presence1_782":"presence.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence1_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence1_782":"presence.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence1_782 -d '{"varid":"presence1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence1_782 -d '{"varname":"presence1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence1_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence1_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence1_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence1_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence1_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence1_782 -d '{"routingkey":"metaforum.floor7.room782.desk1.presence.presence1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence1_782 -d '{"varlocation":"mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk1 -d '{"presence1_782":"presence1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence1_782":"presence1_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk2.presence2_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence2_782 -d '{"serinstid":"serinst.presence2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence2_782 -d '{"serinstname":"presence.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence2_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk2 -d '{"serinst.presence2_782":"presence.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence2_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence2_782":"presence.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence2_782 -d '{"varid":"presence2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence2_782 -d '{"varname":"presence2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence2_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence2_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence2_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence2_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence2_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence2_782 -d '{"routingkey":"metaforum.floor7.room782.desk2.presence.presence2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence2_782 -d '{"varlocation":"mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk2 -d '{"presence2_782":"presence2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence2_782":"presence2_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk3.presence3_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence3_782 -d '{"serinstid":"serinst.presence3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence3_782 -d '{"serinstname":"presence.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence3_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk3 -d '{"serinst.presence3_782":"presence.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence3_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence3_782":"presence.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence3_782 -d '{"varid":"presence3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence3_782 -d '{"varname":"presence3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence3_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence3_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence3_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence3_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence3_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence3_782 -d '{"routingkey":"metaforum.floor7.room782.desk3.presence.presence3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence3_782 -d '{"varlocation":"mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk3 -d '{"presence3_782":"presence3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence3_782":"presence3_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk4.presence4_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence4_782 -d '{"serinstid":"serinst.presence4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence4_782 -d '{"serinstname":"presence.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence4_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk4 -d '{"serinst.presence4_782":"presence.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence4_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence4_782":"presence.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence4_782 -d '{"varid":"presence4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence4_782 -d '{"varname":"presence4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence4_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence4_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence4_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence4_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence4_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence4_782 -d '{"routingkey":"metaforum.floor7.room782.desk4.presence.presence4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence4_782 -d '{"varlocation":"mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk4 -d '{"presence4_782":"presence4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence4_782":"presence4_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk5.presence5_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence5_782 -d '{"serinstid":"serinst.presence5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence5_782 -d '{"serinstname":"presence.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence5_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk5 -d '{"serinst.presence5_782":"presence.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence5_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence5_782":"presence.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence5_782 -d '{"varid":"presence5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence5_782 -d '{"varname":"presence5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence5_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence5_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence5_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence5_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence5_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence5_782 -d '{"routingkey":"metaforum.floor7.room782.desk5.presence.presence5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence5_782 -d '{"varlocation":"mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk5 -d '{"presence5_782":"presence5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence5_782":"presence5_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk6.presence6_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence6_782 -d '{"serinstid":"serinst.presence6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence6_782 -d '{"serinstname":"presence.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence6_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk6 -d '{"serinst.presence6_782":"presence.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence6_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence6_782":"presence.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence6_782 -d '{"varid":"presence6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence6_782 -d '{"varname":"presence6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence6_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence6_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence6_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence6_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence6_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence6_782 -d '{"routingkey":"metaforum.floor7.room782.desk6.presence.presence6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence6_782 -d '{"varlocation":"mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk6 -d '{"presence6_782":"presence6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence6_782":"presence6_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk7.presence7_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence7_782 -d '{"serinstid":"serinst.presence7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence7_782 -d '{"serinstname":"presence.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence7_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk7 -d '{"serinst.presence7_782":"presence.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence7_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence7_782":"presence.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence7_782 -d '{"varid":"presence7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence7_782 -d '{"varname":"presence7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence7_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence7_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence7_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence7_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence7_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence7_782 -d '{"routingkey":"metaforum.floor7.room782.desk7.presence.presence7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence7_782 -d '{"varlocation":"mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk7 -d '{"presence7_782":"presence7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence7_782":"presence7_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk8.presence8_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence8_782 -d '{"serinstid":"serinst.presence8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence8_782 -d '{"serinstname":"presence.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence8_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk8 -d '{"serinst.presence8_782":"presence.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence8_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence8_782":"presence.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence8_782 -d '{"varid":"presence8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence8_782 -d '{"varname":"presence8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence8_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence8_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence8_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence8_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence8_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence8_782 -d '{"routingkey":"metaforum.floor7.room782.desk8.presence.presence8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence8_782 -d '{"varlocation":"mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk8 -d '{"presence8_782":"presence8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence8_782":"presence8_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk9.presence9_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence9_782 -d '{"serinstid":"serinst.presence9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence9_782 -d '{"serinstname":"presence.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence9_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk9 -d '{"serinst.presence9_782":"presence.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence9_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence9_782":"presence.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence9_782 -d '{"varid":"presence9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence9_782 -d '{"varname":"presence9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence9_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence9_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence9_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence9_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence9_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence9_782 -d '{"routingkey":"metaforum.floor7.room782.desk9.presence.presence9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence9_782 -d '{"varlocation":"mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk9 -d '{"presence9_782":"presence9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence9_782":"presence9_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk10.presence10_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence10_782 -d '{"serinstid":"serinst.presence10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence10_782 -d '{"serinstname":"presence.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence10_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk10 -d '{"serinst.presence10_782":"presence.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence10_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence10_782":"presence.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence10_782 -d '{"varid":"presence10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence10_782 -d '{"varname":"presence10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence10_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence10_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence10_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence10_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence10_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence10_782 -d '{"routingkey":"metaforum.floor7.room782.desk10.presence.presence10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence10_782 -d '{"varlocation":"mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk10 -d '{"presence10_782":"presence10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence10_782":"presence10_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk11.presence11_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence11_782 -d '{"serinstid":"serinst.presence11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence11_782 -d '{"serinstname":"presence.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence11_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk11 -d '{"serinst.presence11_782":"presence.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence11_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence11_782":"presence.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence11_782 -d '{"varid":"presence11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence11_782 -d '{"varname":"presence11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence11_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence11_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence11_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence11_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence11_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence11_782 -d '{"routingkey":"metaforum.floor7.room782.desk11.presence.presence11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence11_782 -d '{"varlocation":"mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk11 -d '{"presence11_782":"presence11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence11_782":"presence11_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk12.presence12_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence12_782 -d '{"serinstid":"serinst.presence12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence12_782 -d '{"serinstname":"presence.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence12_782 -d '{"serinstservicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk12 -d '{"serinst.presence12_782":"presence.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.presence12_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/presence -d '{"serinst.presence12_782":"presence.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence12_782 -d '{"varid":"presence12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence12_782 -d '{"varname":"presence12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence12_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence12_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence12_782 -d '{"servicetype":"presence"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence12_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence12_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence12_782 -d '{"routingkey":"metaforum.floor7.room782.desk12.presence.presence12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/presence12_782 -d '{"varlocation":"mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk12 -d '{"presence12_782":"presence12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/presence -d '{"presence12_782":"presence12_782"}' -H 'Content-Type:"application/json"'

