# mf7.82.desk1.deskwork1_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork1_782 -d '{"serinstid":"serinst.deskwork1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork1_782 -d '{"serinstname":"deskwork.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork1_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk1 -d '{"serinst.deskwork1_782":"deskwork.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork1_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork1_782":"deskwork.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork1_782 -d '{"varid":"deskwork1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork1_782 -d '{"varname":"deskwork1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork1_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork1_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork1_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork1_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork1_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork1_782 -d '{"routingkey":"metaforum.floor7.room782.desk1.deskwork.deskwork1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork1_782 -d '{"varlocation":"mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk1 -d '{"deskwork1_782":"deskwork1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork1_782":"deskwork1_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk1.computerwork1_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork1_782 -d '{"serinstid":"serinst.computerwork1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork1_782 -d '{"serinstname":"computerwork.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork1_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk1 -d '{"serinst.computerwork1_782":"computerwork.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork1_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork1_782":"computerwork.mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork1_782 -d '{"varid":"computerwork1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork1_782 -d '{"varname":"computerwork1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork1_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork1_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork1_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork1_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork1_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork1_782 -d '{"routingkey":"metaforum.floor7.room782.desk1.computerwork.computerwork1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork1_782 -d '{"varlocation":"mf7.82.desk1"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk1 -d '{"computerwork1_782":"computerwork1_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork1_782":"computerwork1_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk2.deskwork2_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork2_782 -d '{"serinstid":"serinst.deskwork2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork2_782 -d '{"serinstname":"deskwork.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork2_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk2 -d '{"serinst.deskwork2_782":"deskwork.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork2_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork2_782":"deskwork.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork2_782 -d '{"varid":"deskwork2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork2_782 -d '{"varname":"deskwork2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork2_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork2_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork2_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork2_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork2_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork2_782 -d '{"routingkey":"metaforum.floor7.room782.desk2.deskwork.deskwork2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork2_782 -d '{"varlocation":"mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk2 -d '{"deskwork2_782":"deskwork2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork2_782":"deskwork2_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk2.computerwork2_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork2_782 -d '{"serinstid":"serinst.computerwork2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork2_782 -d '{"serinstname":"computerwork.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork2_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk2 -d '{"serinst.computerwork2_782":"computerwork.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork2_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork2_782":"computerwork.mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork2_782 -d '{"varid":"computerwork2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork2_782 -d '{"varname":"computerwork2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork2_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork2_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork2_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork2_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork2_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork2_782 -d '{"routingkey":"metaforum.floor7.room782.desk2.computerwork.computerwork2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork2_782 -d '{"varlocation":"mf7.82.desk2"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk2 -d '{"computerwork2_782":"computerwork2_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork2_782":"computerwork2_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk3.deskwork3_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork3_782 -d '{"serinstid":"serinst.deskwork3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork3_782 -d '{"serinstname":"deskwork.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork3_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk3 -d '{"serinst.deskwork3_782":"deskwork.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork3_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork3_782":"deskwork.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork3_782 -d '{"varid":"deskwork3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork3_782 -d '{"varname":"deskwork3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork3_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork3_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork3_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork3_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork3_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork3_782 -d '{"routingkey":"metaforum.floor7.room782.desk3.deskwork.deskwork3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork3_782 -d '{"varlocation":"mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk3 -d '{"deskwork3_782":"deskwork3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork3_782":"deskwork3_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk3.computerwork3_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork3_782 -d '{"serinstid":"serinst.computerwork3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork3_782 -d '{"serinstname":"computerwork.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork3_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk3 -d '{"serinst.computerwork3_782":"computerwork.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork3_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork3_782":"computerwork.mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork3_782 -d '{"varid":"computerwork3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork3_782 -d '{"varname":"computerwork3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork3_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork3_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork3_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork3_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork3_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork3_782 -d '{"routingkey":"metaforum.floor7.room782.desk3.computerwork.computerwork3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork3_782 -d '{"varlocation":"mf7.82.desk3"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk3 -d '{"computerwork3_782":"computerwork3_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork3_782":"computerwork3_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk4.deskwork4_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork4_782 -d '{"serinstid":"serinst.deskwork4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork4_782 -d '{"serinstname":"deskwork.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork4_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk4 -d '{"serinst.deskwork4_782":"deskwork.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork4_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork4_782":"deskwork.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork4_782 -d '{"varid":"deskwork4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork4_782 -d '{"varname":"deskwork4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork4_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork4_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork4_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork4_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork4_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork4_782 -d '{"routingkey":"metaforum.floor7.room782.desk4.deskwork.deskwork4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork4_782 -d '{"varlocation":"mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk4 -d '{"deskwork4_782":"deskwork4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork4_782":"deskwork4_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk4.computerwork4_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork4_782 -d '{"serinstid":"serinst.computerwork4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork4_782 -d '{"serinstname":"computerwork.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork4_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk4 -d '{"serinst.computerwork4_782":"computerwork.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork4_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork4_782":"computerwork.mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork4_782 -d '{"varid":"computerwork4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork4_782 -d '{"varname":"computerwork4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork4_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork4_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork4_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork4_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork4_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork4_782 -d '{"routingkey":"metaforum.floor7.room782.desk4.computerwork.computerwork4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork4_782 -d '{"varlocation":"mf7.82.desk4"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk4 -d '{"computerwork4_782":"computerwork4_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork4_782":"computerwork4_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk5.deskwork5_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork5_782 -d '{"serinstid":"serinst.deskwork5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork5_782 -d '{"serinstname":"deskwork.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork5_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk5 -d '{"serinst.deskwork5_782":"deskwork.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork5_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork5_782":"deskwork.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork5_782 -d '{"varid":"deskwork5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork5_782 -d '{"varname":"deskwork5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork5_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork5_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork5_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork5_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork5_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork5_782 -d '{"routingkey":"metaforum.floor7.room782.desk5.deskwork.deskwork5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork5_782 -d '{"varlocation":"mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk5 -d '{"deskwork5_782":"deskwork5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork5_782":"deskwork5_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk5.computerwork5_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork5_782 -d '{"serinstid":"serinst.computerwork5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork5_782 -d '{"serinstname":"computerwork.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork5_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk5 -d '{"serinst.computerwork5_782":"computerwork.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork5_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork5_782":"computerwork.mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork5_782 -d '{"varid":"computerwork5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork5_782 -d '{"varname":"computerwork5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork5_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork5_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork5_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork5_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork5_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork5_782 -d '{"routingkey":"metaforum.floor7.room782.desk5.computerwork.computerwork5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork5_782 -d '{"varlocation":"mf7.82.desk5"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk5 -d '{"computerwork5_782":"computerwork5_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork5_782":"computerwork5_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk6.deskwork6_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork6_782 -d '{"serinstid":"serinst.deskwork6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork6_782 -d '{"serinstname":"deskwork.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork6_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk6 -d '{"serinst.deskwork6_782":"deskwork.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork6_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork6_782":"deskwork.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork6_782 -d '{"varid":"deskwork6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork6_782 -d '{"varname":"deskwork6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork6_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork6_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork6_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork6_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork6_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork6_782 -d '{"routingkey":"metaforum.floor7.room782.desk6.deskwork.deskwork6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork6_782 -d '{"varlocation":"mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk6 -d '{"deskwork6_782":"deskwork6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork6_782":"deskwork6_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk6.computerwork6_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork6_782 -d '{"serinstid":"serinst.computerwork6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork6_782 -d '{"serinstname":"computerwork.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork6_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk6 -d '{"serinst.computerwork6_782":"computerwork.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork6_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork6_782":"computerwork.mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork6_782 -d '{"varid":"computerwork6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork6_782 -d '{"varname":"computerwork6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork6_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork6_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork6_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork6_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork6_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork6_782 -d '{"routingkey":"metaforum.floor7.room782.desk6.computerwork.computerwork6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork6_782 -d '{"varlocation":"mf7.82.desk6"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk6 -d '{"computerwork6_782":"computerwork6_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork6_782":"computerwork6_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk7.deskwork7_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork7_782 -d '{"serinstid":"serinst.deskwork7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork7_782 -d '{"serinstname":"deskwork.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork7_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk7 -d '{"serinst.deskwork7_782":"deskwork.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork7_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork7_782":"deskwork.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork7_782 -d '{"varid":"deskwork7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork7_782 -d '{"varname":"deskwork7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork7_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork7_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork7_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork7_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork7_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork7_782 -d '{"routingkey":"metaforum.floor7.room782.desk7.deskwork.deskwork7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork7_782 -d '{"varlocation":"mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk7 -d '{"deskwork7_782":"deskwork7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork7_782":"deskwork7_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk7.computerwork7_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork7_782 -d '{"serinstid":"serinst.computerwork7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork7_782 -d '{"serinstname":"computerwork.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork7_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk7 -d '{"serinst.computerwork7_782":"computerwork.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork7_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork7_782":"computerwork.mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork7_782 -d '{"varid":"computerwork7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork7_782 -d '{"varname":"computerwork7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork7_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork7_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork7_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork7_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork7_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork7_782 -d '{"routingkey":"metaforum.floor7.room782.desk7.computerwork.computerwork7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork7_782 -d '{"varlocation":"mf7.82.desk7"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk7 -d '{"computerwork7_782":"computerwork7_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork7_782":"computerwork7_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk8.deskwork8_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork8_782 -d '{"serinstid":"serinst.deskwork8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork8_782 -d '{"serinstname":"deskwork.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork8_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk8 -d '{"serinst.deskwork8_782":"deskwork.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork8_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork8_782":"deskwork.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork8_782 -d '{"varid":"deskwork8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork8_782 -d '{"varname":"deskwork8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork8_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork8_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork8_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork8_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork8_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork8_782 -d '{"routingkey":"metaforum.floor7.room782.desk8.deskwork.deskwork8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork8_782 -d '{"varlocation":"mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk8 -d '{"deskwork8_782":"deskwork8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork8_782":"deskwork8_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk8.computerwork8_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork8_782 -d '{"serinstid":"serinst.computerwork8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork8_782 -d '{"serinstname":"computerwork.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork8_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk8 -d '{"serinst.computerwork8_782":"computerwork.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork8_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork8_782":"computerwork.mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork8_782 -d '{"varid":"computerwork8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork8_782 -d '{"varname":"computerwork8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork8_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork8_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork8_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork8_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork8_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork8_782 -d '{"routingkey":"metaforum.floor7.room782.desk8.computerwork.computerwork8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork8_782 -d '{"varlocation":"mf7.82.desk8"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk8 -d '{"computerwork8_782":"computerwork8_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork8_782":"computerwork8_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk9.deskwork9_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork9_782 -d '{"serinstid":"serinst.deskwork9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork9_782 -d '{"serinstname":"deskwork.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork9_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk9 -d '{"serinst.deskwork9_782":"deskwork.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork9_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork9_782":"deskwork.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork9_782 -d '{"varid":"deskwork9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork9_782 -d '{"varname":"deskwork9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork9_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork9_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork9_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork9_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork9_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork9_782 -d '{"routingkey":"metaforum.floor7.room782.desk9.deskwork.deskwork9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork9_782 -d '{"varlocation":"mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk9 -d '{"deskwork9_782":"deskwork9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork9_782":"deskwork9_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk9.computerwork9_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork9_782 -d '{"serinstid":"serinst.computerwork9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork9_782 -d '{"serinstname":"computerwork.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork9_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk9 -d '{"serinst.computerwork9_782":"computerwork.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork9_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork9_782":"computerwork.mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork9_782 -d '{"varid":"computerwork9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork9_782 -d '{"varname":"computerwork9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork9_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork9_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork9_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork9_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork9_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork9_782 -d '{"routingkey":"metaforum.floor7.room782.desk9.computerwork.computerwork9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork9_782 -d '{"varlocation":"mf7.82.desk9"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk9 -d '{"computerwork9_782":"computerwork9_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork9_782":"computerwork9_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk10.deskwork10_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork10_782 -d '{"serinstid":"serinst.deskwork10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork10_782 -d '{"serinstname":"deskwork.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork10_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk10 -d '{"serinst.deskwork10_782":"deskwork.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork10_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork10_782":"deskwork.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork10_782 -d '{"varid":"deskwork10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork10_782 -d '{"varname":"deskwork10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork10_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork10_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork10_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork10_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork10_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork10_782 -d '{"routingkey":"metaforum.floor7.room782.desk10.deskwork.deskwork10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork10_782 -d '{"varlocation":"mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk10 -d '{"deskwork10_782":"deskwork10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork10_782":"deskwork10_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk10.computerwork10_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork10_782 -d '{"serinstid":"serinst.computerwork10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork10_782 -d '{"serinstname":"computerwork.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork10_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk10 -d '{"serinst.computerwork10_782":"computerwork.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork10_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork10_782":"computerwork.mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork10_782 -d '{"varid":"computerwork10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork10_782 -d '{"varname":"computerwork10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork10_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork10_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork10_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork10_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork10_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork10_782 -d '{"routingkey":"metaforum.floor7.room782.desk10.computerwork.computerwork10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork10_782 -d '{"varlocation":"mf7.82.desk10"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk10 -d '{"computerwork10_782":"computerwork10_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork10_782":"computerwork10_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk11.deskwork11_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork11_782 -d '{"serinstid":"serinst.deskwork11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork11_782 -d '{"serinstname":"deskwork.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork11_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk11 -d '{"serinst.deskwork11_782":"deskwork.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork11_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork11_782":"deskwork.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork11_782 -d '{"varid":"deskwork11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork11_782 -d '{"varname":"deskwork11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork11_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork11_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork11_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork11_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork11_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork11_782 -d '{"routingkey":"metaforum.floor7.room782.desk11.deskwork.deskwork11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork11_782 -d '{"varlocation":"mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk11 -d '{"deskwork11_782":"deskwork11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork11_782":"deskwork11_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk11.computerwork11_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork11_782 -d '{"serinstid":"serinst.computerwork11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork11_782 -d '{"serinstname":"computerwork.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork11_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk11 -d '{"serinst.computerwork11_782":"computerwork.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork11_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork11_782":"computerwork.mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork11_782 -d '{"varid":"computerwork11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork11_782 -d '{"varname":"computerwork11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork11_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork11_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork11_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork11_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork11_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork11_782 -d '{"routingkey":"metaforum.floor7.room782.desk11.computerwork.computerwork11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork11_782 -d '{"varlocation":"mf7.82.desk11"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk11 -d '{"computerwork11_782":"computerwork11_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork11_782":"computerwork11_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk12.deskwork12_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork12_782 -d '{"serinstid":"serinst.deskwork12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork12_782 -d '{"serinstname":"deskwork.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork12_782 -d '{"serinstservicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk12 -d '{"serinst.deskwork12_782":"deskwork.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.deskwork12_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/deskwork -d '{"serinst.deskwork12_782":"deskwork.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork12_782 -d '{"varid":"deskwork12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork12_782 -d '{"varname":"deskwork12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork12_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork12_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork12_782 -d '{"servicetype":"deskwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork12_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork12_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork12_782 -d '{"routingkey":"metaforum.floor7.room782.desk12.deskwork.deskwork12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/deskwork12_782 -d '{"varlocation":"mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk12 -d '{"deskwork12_782":"deskwork12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/deskwork -d '{"deskwork12_782":"deskwork12_782"}' -H 'Content-Type:"application/json"'

# mf7.82.desk12.computerwork12_782
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork12_782 -d '{"serinstid":"serinst.computerwork12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork12_782 -d '{"serinstname":"computerwork.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork12_782 -d '{"serinstservicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellserviceinstancesin/mf7.82.desk12 -d '{"serinst.computerwork12_782":"computerwork.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/serviceinstance/serinst.computerwork12_782 -d '{"serinstoperations":[]}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/servicetypeinstances/computerwork -d '{"serinst.computerwork12_782":"computerwork.mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork12_782 -d '{"varid":"computerwork12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork12_782 -d '{"varname":"computerwork12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork12_782 -d '{"controllable":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork12_782 -d '{"domainstates":{"states":[{"name":"false","cost":"0"},{"name":"true","cost":"0"}]}}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork12_782 -d '{"servicetype":"computerwork"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork12_782 -d '{"updatedvalue":"false"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork12_782 -d '{"datatype":"boolean"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork12_782 -d '{"routingkey":"metaforum.floor7.room782.desk12.computerwork.computerwork12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/variables/computerwork12_782 -d '{"varlocation":"mf7.82.desk12"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/cellvariablesin/mf7.82.desk12 -d '{"computerwork12_782":"computerwork12_782"}' -H 'Content-Type:"application/json"'
curl -X PUT http://localhost:7777/data/gbrepository/sertypevariablesin/computerwork -d '{"computerwork12_782":"computerwork12_782"}' -H 'Content-Type:"application/json"'

