#include "repowebpage.h"

repowebpage::repowebpage(){ }
 
repowebpage::~repowebpage(){ }

/*! ***************************************** 
 * A function for the inventorying webpage  *
 ********************************************/
std::string repowebpage::inventorying_headerpage(){

	std::ostringstream sout512;
	  sout512 << "<html> "
		<< " <head> "
		<< " 	<title>Invontorying Module of the REPOSITORY</title> "
		<< " </head> "
		<< " <body> "
		<< " 	<p> "
		<< " 	&quot; "
		<< " 	<style type=\"text/css\"> "
		<< " body {background-color:#CCFF99;background-repeat:no-repeat;background-position:top left;background-attachment:fixed;} "
		<< "  	   h1{font-family:Impact;color:006600;} "
		<< "  	   p {font-family:Georgia;font-size:14px;font-style:normal;font-weight:normal;color:00000			</style> "
		<< " 	</p> "
		<< " 	<table border=\"1\" cellpadding=\"1\" cellspacing=\"1\" height=\"164\" width=\"884\"> "
		<< " 		<tbody> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					<h2 style=\"text-align: center; font-size:24px;color:orange;text-shadow:1px 1px 1px #000;\"> "
		<< " 					<a href=\"http://www.greenerbuildings.eu/\" target=\"_parent\"><img alt=\"gblogo\""
		<< " src=\"https://lh3.googleusercontent.com/-Dfh1Up_t608/UFGur4C-muI/AAAAAAAAACY/8DTI1WkxMCk/s144/gblog2.png\" "
		<< "style=\"width: 150px; height: 150px; border-width: 1px; border-style: solid; margin: 1px; float: left;\" />"
		<< "</a>Welcome to the Invontroying Module of the REPOSITORY component of the <span style=\"color:#008000;\"> GREENERBUILDINGS </span>architecture.</h2>"
		<< " 				</td> "
		<< " 			</tr> "
		<< " 		</tbody> "
		<< " 	</table> "
		<< " 	<hr /> " 
		<< "<span style=\"font-size:20px;\"><strong>REPOSITORY's Online Inventory Form</strong></span></p> "
		/* FORM starts here */	
		<< "<br/>Select one inventory type <br/> and fill the respective form below <br/>"	
		<< "<form action='/form_handler' method='post'> "
		<< "<SELECT multiple size=\"6\" name='invensele'>"
		<< "<OPTION selected value=\"bldcells\">Building Description (cells)</OPTION>"
		<< "<OPTION selected value=\"serty\">Service Types</OPTION>"
		<< "<OPTION selected value=\"serinst\">Service Instances</OPTION>"
		<< "<OPTION selected value=\"devi\">Devices</OPTION>"
		<< "<OPTION selected value=\"vars\">Variables</OPTION>"
		<< "</SELECT> <br/><br/>"

		/* Building Description Form*/
		<< "<strong> Building Description Form</strong> <br/>"
                << "cellname: &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp <input name='cellname' type='text'><br>  "
                << "cellid: &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp<input name='cellid' type='text'> <br>"
		<< "celltype: &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp<input name='celltype' type='text'> <br>"
		<< "locatation(cellid): <input name='celloc' type='text'> <br><br/>"

		/* Service Type Form*/
		<< "<strong> Service Type Form</strong> <br/>"
                << "service name: &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp<input name='sername' type='text'><br>  "
                << "service id: &nbsp  &nbsp  &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp <input name='serid' type='text'> <br>"
		<< "service type operations: <input name='sertyops' type='text'> <br>"
		<< "ser-type-location(cellid): <input name='sertyloc' type='text'> <br><br/>"

		/* Service Instance Form*/
		<< "<strong> Service Instance Form</strong> <br/>"
                << "service instance name: &nbsp &nbsp &nbsp &nbsp<input name='serinstname' type='text'><br>  "
                << "service instance id: &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp <input name='serinstid' type='text'> <br>"
		<< "service type: &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp <input name='serinsttype' type='text'> <br>"
		<< "service instance binding: &nbsp &nbsp <input name='serinstbinding' type='text'> <br>"
		<< "service instance effective: &nbsp &nbsp<input name='serinsteffec' type='text'> <br>"
		<< "ser-instan-location(cellid): &nbsp <input name='serinstloc' type='text'> <br><br/>"

		/* Variables Form*/
		<< "<strong> Variables Form</strong> <br/>"
                << "variable name: &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp<input name='varname' type='text'><br>  "
                << "variable id: &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp <input name='varid' type='text'> <br>"
		<< "variable contrabality: &nbsp &nbsp &nbsp &nbsp<input name='varcontrblty' type='text'> <br>"
		<< "variable domain states: &nbsp &nbsp <input name='vardomainstate' type='text'> <br>"
		<< "variable-location(cellid): &nbsp <input name='varloc' type='text'> <br><br/>"

		/* the submit button*/
		<< " <input type='submit' value= 'submit your inventory' /> "
                << " </form>"
		<< "	<p> "
		<< "		&nbsp;</p> " << std::endl;		

 return sout512.str();
}



/*! *********************************************** 
 *  Functions for the online test module webpage  *
 **************************************************/

/* Test module header webpage*/
std::string repowebpage::testmodule_headerpage(){

	std::ostringstream sout51;
	  sout51 << "<html> "
		<< " <head> "
		<< " 	<title>Test Module for the REPOSITORY</title> "
		<< " </head> "
		<< " <body> "
		<< " 	<p> "
		<< " 	&quot; "
		<< " 	<style type=\"text/css\"> "
		<< " body {background-color:#CCFF99;background-repeat:no-repeat;background-position:top left;background-attachment:fixed;} "
		<< "  	   h1{font-family:Impact;color:006600;} "
		<< "  	   p {font-family:Georgia;font-size:14px;font-style:normal;font-weight:normal;color:00000			</style> "
		<< " 	</p> "
		<< " 	<table border=\"1\" cellpadding=\"1\" cellspacing=\"1\" height=\"164\" width=\"884\"> "
		<< " 		<tbody> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					<h2 style=\"text-align: center; font-size:24px;color:orange;text-shadow:1px 1px 1px #000;\"> "
		<< " 					<a href=\"http://www.greenerbuildings.eu/\" target=\"_parent\"><img alt=\"gblogo\" "
		<< "src=\"https://lh3.googleusercontent.com/-Dfh1Up_t608/UFGur4C-muI/AAAAAAAAACY/8DTI1WkxMCk/s144/gblog2.png\" "
		<< "style=\"width: 150px; height: 150px; border-width: 1px; border-style: solid; margin: 1px; float: left;\" />"
		<< "</a>Welcome to the Test Module of the REPOSITORY component of the <span style=\"color:#008000;\"> GREENERBUILDINGS </span>architecture.</h2>"
		<< " 				</td> "
		<< " 			</tr> "
		<< " 		</tbody> "
		<< " 	</table> "
		<< " 	<hr /> " 
		<< "<p style=\"font-size:20px;color:orange;text-shadow:1px 1px 1px #000;\"> "
		<< "<span style=\"font-size:20px;\"><strong>Test your Queries Online</strong></span></p> "
		<< " <p>query format for this test module is: [REST_COMMAND] [http://localhost:5000/QUERYTYPE/KEYSPACE/COLUMNFAMILY/ROWKEY/COLUMNNAME/]  </p>"
		<< " <p>where[REST_COMMAND]=[PUT/POST/GET/DELETE], QUERYTYPE=[data/search], in which data is used with GET and PUT and search is used with POST  </p>"
		<< " <p>Note that, it is not neccessary to add the http header(-H &#39;Content-Type:&quot;application/json&quot;&#39) for this test purpose. In addition, add \"/\" at the end of your URI  </p>"
		<< "<form action='/form_handler' method='post'> "
	 	<< "<form action='/form_handler' method='post'> "
		<< "<textarea name=\"restquery\" cols=\"100\" rows=\"5\" style=\"background-color:#FCF5D8;color:#AD8C08;\">"
		<< "Enter your REST based query here ..... then click submit to see response"
		<< "</textarea>"
		<< "<br /> "
		<< " <input type=\"submit\" value=\"submit your query\" /> "
		<< " </form> "
		<< "	<p> "
		<< "		&nbsp;</p> " << std::endl;		

 return sout51.str();
}

/********** Test module tips page *****************/
std::string repowebpage::testmodule_tipspage(){

	std::ostringstream sout5;
	  sout5 << " <p style=\"font-size:20px;color:orange;text-shadow:1px 1px 1px #000;\"> "
		<< "	<strong>Tips</strong> </p> "
		<< "<ul> "
		<< "	<li> "
		<< "		to write a column: "
		<< "	<ul> "
		<< "		<li> "
		<< "			PUT <strong>http://IP:Port/data/gbrepository</strong>/yourcolomnfamily/yourrowkey/ -d &#39;{&quot;yourcolname&quot;:&quot;yourcolvalue&quot;}&#39;</li> "
		<< "	</ul> "
		<< "	</li> "
		<< "	<li> "
		<< "		to read a column: "
		<< "		<ul> "
		<< "			<li> "
		<< "				GET <strong>http://IP:Port/data/gbrepository</strong>/yourcolomnfamily/yourrowkey/yourcolname/</li> "
		<< "		</ul> "
		<< "	</li> "
		<< "	<li> "
		<< "		to read entire row "
		<< "		<ul> "
		<< "			<li> "
		<< "				GET <strong>http://IP:Port/data/gbrepository</strong>/yourcolomnfamily/yourrowkey/</li> "
		<< "		</ul> "
		<< "	</li> "
		<< "	<li> "
		<< "		to execute CQL (search): "
		<< "		<ul> "
		<< "			<li> "
		<< "				POST <strong>http://IP:Port/data/gbrepository</strong>/ -d &#39;{&quot;CQL&quot;:&quot;your cql command&quot;}&#39;</li> "
		<< "		</ul> "
		<< "	</li> "
		<< "	<li> "
		<< "		...and much more!</li> "
		<< " </ul> <hr/>" << std::endl;		

 return sout5.str();
}

/*! Test module basic page */
std::string repowebpage::testmodule_basicpage(){

	std::ostringstream sout4;
	  sout4 << "    <p style=\"font-size:20px;color:orange;text-shadow:1px 1px 1px #000;\"> "
		/* DATA STRUCTURE*/
		<< "	<strong>Data Structure</strong> </p> "	
		<< " 	<p> "
		<< " 		The Repository component is implemented with Apache Cassandra database.<br /> "
		<< " 		It has one keyspace called gbrepository and several column families under it. The data stored are structured in the following groups:</p> "
		<< " 	<ol> "
		<< " 		<li> "
		<< " 			Building description data</li> "
		<< " 		<li> "
		<< " 			Service types data</li> "
		<< " 		<li> "
		<< " 			Service instances data</li> "
		<< " 		<li> "
		<< " 			Devices data</li> "
		<< " 		<li> "
		<< " 			Variables data</li> "
		<< " 		<li> "
		<< " 			Historical context data</li> "
		<< " 	</ol> "
		<< " 	<p> "
		<< " 		Furthermore, the REPOSITORY offers the following functionalities:</p> "
		<< " 	<ol> "
		<< " 		<li> "
		<< " 			Echo on probe (http://domonica.ele.tue.nl:5000/data/gbrepository/api/echo ) </li> "
		<< " 		<li> "
		<< " 			Statistics and snapshot (http://domonica.ele.tue.nl:5000/data/gbrepository/api/stat )</li> "
		<< " 		<li> "
		<< " 			Zookeeper registration</li> "
		<< " 		<li> "
		<< " 			Read/Write/Modify/Delete data</li> "
		<< " 		<li> "
		<< " 			Search data</li> "
		<< " 	</ol> "
		/* DATA MODEL*/
		<< " 	<p style=\"font-size:20px;color:orange;text-shadow:1px 1px 1px #000;\"> "
		<< " 		<span style=\"font-size:20px;\"><strong>Data Model</strong></span></p> "
		<< " 	<ol start=\"1\" style=\"list-style-type: upper-roman;\"> "
		<< " 		<li> "
		<< " 			Keyspace: <span style=\"color:#008000;\">gbrepository</span>.</li> "
		<< " 		<li> "
		<< " 			<strong>Building description</strong> related Column Families: the row key for building related column families is a unique ID of a cell, eg. room326, room3261 ..... "
		<< " 			<table align=\"center\" border=\"1\" cellpadding=\"1\" cellspacing=\"1\" height=\"474\" width=\"585\"> "
		<< " 				<tbody> "
		<< " 					<tr> "
		<< " 						<td> "
		<< " 							&nbsp;</td> "
		<< " 						<td style=\"text-align: center;\"> "
		<< " 							Column Family name</td> "
		<< " 						<td style=\"text-align: center;\"> "
		<< " 							description</td> "
		<< " 					</tr> "
		<< " 					<tr> "
		<< " 						<td> "
		<< " 							1.</td> "
		<< " 						<td> "
		<< " 							<span style=\"color:#008000;\">cells</span></td> "
		<< " 						<td> "
		<< " 							containas basic information such as cell ID and cell name.</td> "
		<< " 					</tr> "
		<< " 					<tr> "
		<< " 						<td> "
		<< " 							2.</td> "
		<< " 						<td> "
		<< " 							<span style=\"color:#008000;\">celltype </span></td> "
		<< " 						<td> "
		<< " 							to be defined .....</td> "
		<< " 					</tr> "
		<< " 					<tr> "
		<< " 						<td> "
		<< " 							3.</td> "
		<< " 						<td> "
		<< " 							<span style=\"color:#008000;\">cellsinside</span></td> "
		<< " 						<td> "
		<< " 							contians columns of cells inside a psecific cell. The columns are in the form of {&quot;cellid&quot;:&quot;cellname&quot;}, i.e. column name is represents the unique ID of the&nbsp; and column value gives the name of the cell that is inside.</td> "
		<< " 					</tr> "
		<< " 					<tr> "
		<< " 						<td> "
		<< " 							4.</td> "
		<< " 						<td> "
		<< " 							<span style=\"color:#008000;\">celldevicesin </span></td> "
		<< " 						<td> "
		<< " 							contains columns of all devices inside a cell. Each column is represented with {&quot;device ID&quot;:&quot;device name&quot;}</td> "
			<< " 				</tr> "
			<< " 				<tr> "
			<< " 					<td> "
			<< " 						5.</td> "
			<< " 					<td> "
			<< " 						<span style=\"color:#008000;\">cellservicetypesin</span></td> "
			<< " 					<td> "
			<< " 						contains columns of all service types that are available in a cell. Each column is represented with {&quot;service type ID&quot;:&quot;service type name&quot;}</td> "
			<< " 				</tr> "
			<< " 				<tr> "
			<< " 					<td> "
			<< " 						6.</td> "
			<< " 					<td> "
			<< " 						<span style=\"color:#008000;\">cellserviceinstancesin</span></td> "
			<< " 					<td> "
			<< " 						contains columns of all serviceinstances that are available in a cell. Each column is represented with {&quot;service type ID&quot;:&quot;service type name&quot;}</td> "
			<< " 				</tr> "
			<< " 				<tr> "
			<< " 					<td> "
			<< " 						7.</td> "
			<< " 					<td> "
			<< " 						<span style=\"color:#008000;\">cellvariablesin</span></td> "
			<< " 					<td> "
			<< " 						contains columns of all variables related to a cell in the form of columns represented as {&quot;variable ID&quot;:&quot;variable name&quot;}</td> "
			<< " 				</tr> "
			<< " 				<tr> "
			<< " 					<td> "
			<< " 						8.</td> "
			<< " 					<td> "
			<< " 						<span style=\"color:#008000;\">cellproperties</span></td> "
			<< " 					<td> "
			<< " 						&nbsp;to be defined in detail</td> "
			<< " 				</tr> "
			<< " 			</tbody> "
			<< " 		</table> "
			<< " 	</li> "
		<< " 	</ol> "
		<< " 	<p> "
		<< " 		&nbsp;</p> "
		<< " 	<ol start=\"3\" style=\"list-style-type: upper-roman;\"> "
		<< " 		<li> "
		<< " 			<strong>Service types</strong> related column families: These column families will have a unique servie type ID as a row key such as ser1, ser2, ser3 ...</li> "
		<< " 	</ol> "
		<< " 	<table align=\"center\" border=\"1\" cellpadding=\"1\" cellspacing=\"1\" height=\"233\" width=\"585\"> "
		<< " 		<tbody> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 				<td style=\"text-align: center;\"> "
		<< " 					Column Family name</td> "
		<< " 				<td style=\"text-align: center;\"> "
		<< " 					description</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					1.</td> "
		<< " 				<td> "
		<< " 					<span style=\"color:#008000;\">servicetype</span></td> "
		<< " 				<td> "
		<< " 					containas information about service types such as service type ID and service type name, and servicetypeoperations.</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					2.</td> "
		<< " 				<td> "
		<< " 					<span style=\"color:#008000;\">sertypevariablesin</span></td> "
		<< " 				<td> "
		<< " 					contains columns of all variables in a service types. Each column is represented with {&quot;variable ID&quot;:&quot;variable name&quot;}</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					3.</td> "
		<< " 				<td> "
		<< " 					<span style=\"color:#008000;\">servicetypeinstances</span></td> "
		<< " 				<td> "
		<< " 					contains columns of all service instances of a service type. Each column is represented with {&quot;service instance ID&quot;:&quot;service instance name&quot;}</td> "
		<< " 			</tr> "
		<< " 		</tbody> "
		<< " 	</table> "
		<< " 	<p> "
		<< " 		&nbsp;</p> "
		<< " 	<ol start=\"4\" style=\"list-style-type: upper-roman;\"> "
		<< " 		<li> "
		<< " 			<strong>Service instances</strong> related column families: Similar to the above column famileis, service instancea also have a unique ID that is used as a row key.</li> "
		<< " 	</ol> "
		<< " 	<table align=\"center\" border=\"1\" cellpadding=\"1\" cellspacing=\"1\" height=\"233\" width=\"585\"> "
		<< " 		<tbody> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 				<td style=\"text-align: center;\"> "
		<< " 					Column Family name</td> "
		<< " 				<td style=\"text-align: center;\"> "
		<< " 					description</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					1.</td> "
		<< " 				<td> "
		<< " 					<span style=\"color:#008000;\">serviceinstance</span></td> "
		<< " 				<td> "
		<< " 					containas group information related to a service instance such as service instance ID, service instance name, service type in which it belongs, and service instance operations.</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					2.</td> "
		<< " 				<td> "
		<< " 					<span style=\"color:#008000;\">serinstancebindings </span></td> "
		<< " 				<td> "
		<< " 					&nbsp;to be defined</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					3.</td> "
		<< " 				<td> "
		<< " 					<span style=\"color:#008000;\">serinstanceeffective</span></td> "
		<< " 				<td> "
		<< " 					to be defined</td> "
		<< " 			</tr> "
		<< " 		</tbody> "
		<< " 	</table> "
		<< " 	<p> "
		<< " 		&nbsp;</p> "
		<< " 	<ol start=\"5\" style=\"list-style-type: upper-roman;\"> "
		<< " 		<li> "
		<< " 			<strong>Devices </strong>related column families: Similarly, devices also have a unique ID that is used as a row key.</li> "
		<< " 	</ol> "
		<< " 	<table align=\"center\" border=\"1\" cellpadding=\"1\" cellspacing=\"1\" height=\"233\" width=\"585\"> "
		<< " 		<tbody> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 				<td style=\"text-align: center;\"> "
		<< " 					Column Family name</td> "
		<< " 				<td style=\"text-align: center;\"> "
		<< " 					description</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					1.</td> "
		<< " 				<td> "
		<< " 					<span style=\"color:#008000;\">devices</span></td> "
		<< " 				<td> "
		<< " 					containas basic information such as device ID, device name.</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					2.</td> "
		<< " 				<td> "
		<< " 					<span style=\"color:#008000;\">devproperties</span></td> "
		<< " 				<td> "
		<< " 					contains group of columns which represent the properties of device such as its power consumption. (for details ..to be defined )</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					3.</td> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 			</tr> "
		<< " 		</tbody> "
		<< " 	</table> "
		<< " 	<p> "
		<< " 		&nbsp;</p> "
		<< " 	<ol start=\"6\" style=\"list-style-type: upper-roman;\"> "
		<< " 		<li> "
		<< " 			<strong>Variables </strong>related column families: All variables also have a unique ID that is used as a row key.</li> "
		<< " 	</ol> "
		<< " 	<table align=\"center\" border=\"1\" cellpadding=\"1\" cellspacing=\"1\" height=\"233\" width=\"585\"> "
		<< " 		<tbody> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 				<td style=\"text-align: center;\"> "
		<< " 					Column Family name</td> "
		<< " 				<td style=\"text-align: center;\"> "
		<< " 					description</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					1.</td> "
		<< " 				<td> "
		<< " 					<span style=\"color:#008000;\">variables</span></td> "
		<< " 				<td> "
		<< " 					It is a collection of columns related to variables such as, variable id, variable name, updatedvalue of variable, datatype, domainstates, routing key for rabitMq, service type it belong, and variable controllabaility (boolean).</td> "
		<< " 			</tr> "		
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					2.</td> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 			</tr> "
		<< " 		</tbody> "
		<< " 	</table> "
		<< " 	<p> "
		<< " 		&nbsp;</p> "
		<< " 	<ol start=\"7\" style=\"list-style-type: upper-roman;\"> "
		<< " 		<li> "
		<< " 			<strong>Historical data </strong>related column families: This part will be defined later.</li> "
		<< " 	</ol> "
		<< " 	<p> "
		<< " 		&nbsp;</p> "
		<< " 	<table align=\"center\" border=\"1\" cellpadding=\"1\" cellspacing=\"1\" height=\"97\" width=\"585\"> "
		<< " 		<tbody> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 				<td style=\"text-align: center;\"> "
		<< " 					Column Family name</td> "
		<< " 				<td style=\"text-align: center;\"> "
		<< " 					description</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					1.</td> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					2.</td> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 			</tr> "
		<< " 			<tr> "
		<< " 				<td> "
		<< " 					3.</td> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 				<td> "
		<< " 					&nbsp;</td> "
		<< " 			</tr> "
		<< " 		</tbody> "
		<< " 	</table> "
		<< " 	<hr /> "
		/* EXAMPLE QUERIES */
		<< " 	<p style=\"font-size:20px;color:orange;text-shadow:1px 1px 1px #000;\"> "
		<< " 		<span style=\"font-size:20px;\"><strong>Example Queries</strong></span></p> "
		<< "<p>Note that in  the actual queries from your components, use the hostname:port == http://domonica.ele.tue.nl:5000</p>"
		<< " 	<ul> "
		<< " 		<li> "
		<< " 			Given me the service instances in location x(pt3_3.26_desk4)</li> "
		<< " 	</ul> "
		<< " 	<pre style=\"margin-left: 40px;\"> "
		<< " 	<span style=\"background-color:#afeeee;\">GET http://127.0.0.1:5000/data/gbrepository/cellserviceinstancesin/pt3_3.26_desk4/ -H &#39;Content-Type:&quot;application/json&quot;&#39; "
	<< " </span></pre> "
	<< " 		<ul> "
	<< " 			<li> "
	<< " 				Given me all service instances per cell basis(for all locations)</li> "
	<< " 		</ul> "
	<< " 		<pre style=\"margin-left: 40px;\"> "
	<< " 		<span style=\"background-color:#afeeee;\">POST http://127.0.0.1:5000/search/gbrepository/ -d &#39;{&quot;CQL&quot;:&quot;SELECT * FROM cellserviceinstancesin&quot;}&#39;-H &#39;Content-Type:&quot;application/json&quot;&#39; </span></pre> "
	<< " 		<ul> "
	<< " 			<li> "
	<< " 				Give me all variables in location x (pt3_3.26_desk4)</li> "
	<< " 		</ul> "
	<< " 		<pre style=\"margin-left: 40px;\"> "
	<< " 		<span style=\"background-color:#afeeee;\">GET http://127.0.0.1:5000/data/gbrepository/cellvariablesin/pt3_3.26_desk4/ -H &#39;Content-Type:&quot;application/json&quot;&#39; </span></pre> "
	<< " 		<ul> "
	<< " 			<li> "
	<< " 				Given me all variables per cell (for all locations)</li> "
	<< " 		</ul> "
	<< " 		<pre style=\"margin-left: 40px;\"> "
	<< " 		<span style=\"background-color:#afeeee;\">POST http://127.0.0.1:5000/search/gbrepository/ -d &#39;{&quot;CQL&quot;:&quot;SELECT * FROM cellvariablesin&quot;}&#39; -H &#39;Content-Type:&quot;application/json&quot;&#39; </span></pre> "
	<< " 			<li> "
	<< " 				Given me all available variables with all their properties </li> "
	<< " 		</ul> "
	<< " 		<pre style=\"margin-left: 40px;\"> "
	<< " 		<span style=\"background-color:#afeeee;\">POST http://127.0.0.1:5000/search/gbrepository/ -d &#39;{&quot;CQL&quot;:&quot;SELECT * FROM variables&quot;}&#39; -H &#39;Content-Type:&quot;application/json&quot;&#39; </span></pre> "
	<< " 			<li> "
	<< " 				Given me all variables with their variable name, service type and updated value,</li> "
	<< " 		</ul> "
	<< " 		<pre style=\"margin-left: 40px;\"> "
	<< " 		<span style=\"background-color:#afeeee;\">POST http://127.0.0.1:5000/search/gbrepository/ -d &#39;{&quot;CQL&quot;:&quot;SELECT varname, servicetype, updatedvalue FROM variables&quot;}&#39; -H &#39;Content-Type:&quot;application/json&quot;&#39; </span></pre> "
	<< " 		<ul> "
	<< " 			<li> "
	<< " 				Give me all possible operations of a service type = presence</li> "
	<< " 		</ul> "
	<< " 		<pre style=\"margin-left: 40px;\"> "
	<< " 		<span style=\"background-color:#afeeee;\">GET http://127.0.0.1:5000/data/gbrepository/servicetype/presence/sertypeoperations/ -H &#39;Content-Type:&quot;application/json&quot;&#39; </span></pre> "
	<< " 		<ul> "
	<< " 			<li> "
	<< " 				Give me all states of a particular variable (luxlevl1_326)</li> "
	<< " 		</ul> "
	<< " 		<pre style=\"margin-left: 40px;\"> "
	<< " 		<span style=\"background-color:#afeeee;\">GET http://127.0.0.1:5000/data/gbrepository/variables/luxlevel1_326/domainstates/ -H &#39;Content-Type:&quot;application/json&quot;&#39; </span></pre> "
	<< " 		<ul> "
	<< " 			<li> "
	<< " 				Give me the updated value of a particular variable and the time it is updated(luxlevl1_326)</li> "
	<< " 		</ul> "
	<< " 		<pre style=\"margin-left: 40px;\"> "
	<< " 		<span style=\"background-color:#afeeee;\">GET http://127.0.0.1:5000/data/gbrepository/variables/luxlevel1_326/updatedvalue/ -H &#39;Content-Type:&quot;application/json&quot;&#39; </span></pre> "
	<< " 		<ul> "
	<< " 			<li> "
	<< " 				Give me the service instances in location Y with Type X and (Type Y or Type Z)</li> "
	<< " 		</ul> "
	<< " 		<p style=\"margin-left: 40px;\"> "
	<< " 			&nbsp;</p> "
	<< " 		<ul> "
	<< " 			<li> "
	<< " 				Given me the preferred goal of variable A</li> "
	<< " 			<li> "
	<< " 				Give me all possible effects in location x</li> "
	<< " 			<li> "
	<< " 				Give me all possible states of a variable for a certain service type/service instance</li> "
	<< " 			<li> "
	<< " 				Give me all variables for all service types/instances (probably in a certain location)</li> "
	<< " 			<li> "
	<< " 				Give me a cost (energy consumption) of a certain state of a certain variable</li> "
	<< " 		</ul> "
	<< " 		<p> "
	<< " 			&nbsp;</p> "
	<< " 		<hr /> " << std::endl;

return sout4.str();
}

/*! webpage for the column family cells   */
std::string repowebpage::testmodule_cf_cells_page(){

	std::ostringstream sout_cells;
	  sout_cells <<  " <p>"
<<  " 			&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Table 1. Data related to collumn family <strong>cells</strong>, which has two columns, cellname and cellid.</p>"
<< "<hr/> " << std::endl;
 return sout_cells.str();
}

/*  webpage for the column family celltypes */
std::string repowebpage::testmodule_cf_celltypes_page(){

	std::ostringstream sout_celltypes;
	  sout_celltypes <<  " <p>"
<<  " 			&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Table 2. Data related to collumn family <strong>celltypes</strong>, which has columns as many as the number of cells inside it</p>"
<< "<hr/> " << std::endl;
  
 return sout_celltypes.str();
}

/*  webpage for the column family cellsinside */
std::string repowebpage::testmodule_cf_cellsinside_page(){

	std::ostringstream sout_cellsinside;
	  sout_cellsinside <<  " <p>"
<<  " 			&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Table 3. Data related to collumn family <strong>cellsinside</strong>.</p>"
<< "<hr/> " << std::endl;

 return sout_cellsinside.str();
}


/*!  webpage for the column family celldevicesin */
std::string repowebpage::testmodule_cf_celldevicesin_page(){

	std::ostringstream sout_celldevicesin;
	  sout_celldevicesin <<  " <p>"
<<  " 			&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; Table 4. Data related to collumn family <strong>celldevicesin</strong>.</p>"
<< "<hr/> " << std::endl;
  
 return sout_celldevicesin.str();
}



